name: graduate_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  animations: ^2.0.7
  cached_network_image: ^3.2.3

  auto_route: ^7.8.4
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  firebase_messaging: ^14.7.1
  firebase_storage: ^11.5.1
  cloud_firestore: ^4.11.0
  collection: ^1.17.1
  get_it: ^7.6.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  path_provider: ^2.0.15
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  hooks_riverpod: ^2.4.4
  connectivity_plus: ^5.0.1
  flutter_spinkit: ^5.2.0
  gap: ^3.0.1
  simple_logger: ^1.9.0+2
  geolocator: ^10.1.0
  url_launcher: ^6.1.12
  popup_menu: ^2.0.0
  shared_preferences: ^2.2.2
  flutter_hooks: ^0.20.3
  fpdart: ^1.1.0
  uuid: ^3.0.7
  intl: ^0.18.1
  geocoding: ^2.1.1
  provider: ^6.1.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
