name: graduate_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  animations: ^2.0.7
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  cached_network_image: ^3.2.3

  auto_route: ^7.5.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  firebase_messaging: ^14.6.4
  firebase_storage: ^11.2.4
  cloud_firestore: ^4.8.1
  collection: ^1.17.1
  get_it: ^7.6.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  path_provider: ^2.0.15
  image_cropper: ^4.0.1
  image_picker: ^1.0.0
  hooks_riverpod: ^2.3.6
  connectivity_plus: ^4.0.1
  flutter_spinkit: ^5.2.0
  gap: ^3.0.1
  simple_logger: ^1.9.0+2
  geolocator: ^9.0.2
  url_launcher: ^6.1.12
  popup_menu: ^2.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
