// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return web;
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for windows - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIzSqafQVtMQJi-6FTi-CZ6IEYKV0DWBk',
    appId: '1:30376339764:web:9533ae260fd98e761e9d61',
    messagingSenderId: '30376339764',
    projectId: 'emergency-message-app-c8db9',
    authDomain: 'emergency-message-app-c8db9.firebaseapp.com',
    databaseURL:
        'https://emergency-message-app-c8db9-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-message-app-c8db9.appspot.com',
    measurementId: 'G-WNFBC9G4ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyGmDNNCQyGh5DMeZaElMjfZiehEOC10g',
    appId: '1:30376339764:android:c9fb1b834c63c8b41e9d61',
    messagingSenderId: '30376339764',
    projectId: 'emergency-message-app-c8db9',
    databaseURL:
        'https://emergency-message-app-c8db9-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-message-app-c8db9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCrmt2QZmqn0bzQxd4hUNS9qYqnxNA6Uo',
    appId: '1:30376339764:ios:efc7b32cd38b27711e9d61',
    messagingSenderId: '30376339764',
    projectId: 'emergency-message-app-c8db9',
    databaseURL:
        'https://emergency-message-app-c8db9-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-message-app-c8db9.appspot.com',
    androidClientId:
        '30376339764-stt05icstci7mcunjglb46jic72i48uh.apps.googleusercontent.com',
    iosClientId:
        '30376339764-l59t4cf4ij03q11q5g3lnmbucqfck8ic.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduateApp',
  );
}
